#ifndef FORTDEF_H
#define FORTDEF_H

enum FortLogType {
    FORT_LOG_TYPE_NONE = 0,
    FORT_LOG_TYPE_APP,
    FORT_LOG_TYPE_CONN,
    FORT_LOG_TYPE_PROMPT,
    FORT_LOG_TYPE_PROC_NEW,
    FORT_LOG_TYPE_STAT_TRAF,
    FORT_LOG_TYPE_TIME,
};

enum FortLogConnFlag {
    FORT_LOG_CONN_IP6 = (1 << 0),
    FORT_LOG_CONN_INBOUND = (1 << 1),
    FORT_LOG_CONN_INHERITED = (1 << 2),
};

enum FortConnReason {
    FORT_CONN_REASON_UNKNOWN = 0,
    FORT_CONN_REASON_IP_INET,
    FORT_CONN_REASON_REAUTH,
    FORT_CONN_REASON_PROGRAM,
    FORT_CONN_REASON_APP_GROUP,
    FORT_CONN_REASON_FILTER_MODE,
    FORT_CONN_REASON_LAN_ONLY,
    FORT_CONN_REASON_ZONE,
    FORT_CONN_REASON_RULE,
    FORT_CONN_REASON_RULE_GLOB_PRE,
    FORT_CONN_REASON_RULE_GLOB_POST,
    FORT_CONN_REASON_ASK_LIMIT,
    FORT_CONN_REASON_ASK_PENDING = 15 /* must be last one! */
};

#endif // FORTDEF_H
