/* Fort Firewall Driver Loader: Proxy Callbacks: Source */

#include "fortpcb_src.h"

static ProxyCallbackProc g_proxySrcCallbacks[PROXY_CALLBACKS_COUNT] = {
    proxyCallback0,
    proxyCallback1,
    proxyCallback2,
    proxyCallback3,
    proxyCallback4,
    proxyCallback5,
    proxyCallback6,
    proxyCallback7,
    proxyCallback8,
    proxyCallback9,
    proxyCallback10,
    proxyCallback11,
    proxyCallback12,
    proxyCallback13,
    proxyCallback14,
    proxyCallback15,
    proxyCallback16,
    proxyCallback17,
    proxyCallback18,
    proxyCallback19,
    proxyCallback20,
    proxyCallback21,
    proxyCallback22,
    proxyCallback23,
    proxyCallback24,
    proxyCallback25,
    proxyCallback26,
    proxyCallback27,
    proxyCallback28,
    proxyCallback29,
    proxyCallback30,
    proxyCallback31,
    proxyCallback32,
    proxyCallback33,
    proxyCallback34,
    proxyCallback35,
    proxyCallback36,
    proxyCallback37,
    proxyCallback38,
    proxyCallback39,
    proxyCallback40,
    proxyCallback41,
    proxyCallback42,
    proxyCallback43,
    proxyCallback44,
    proxyCallback45,
    proxyCallback46,
    proxyCallback47,
    proxyCallback48,
    proxyCallback49,
    proxyCallback50,
    proxyCallback51,
    proxyCallback52,
    proxyCallback53,
    proxyCallback54,
    proxyCallback55,
    proxyCallback56,
    proxyCallback57,
    proxyCallback58,
    proxyCallback59,
    proxyCallback60,
    proxyCallback61,
    proxyCallback62,
    proxyCallback63,
};

FORT_API void fort_proxycb_src_setup(void)
{
    DbgPrintEx(DPFLTR_IHVNETWORK_ID, DPFLTR_ERROR_LEVEL, "FORT: ProxyCbSrc Setup: %p\n",
            &proxyCallback0);
}
